// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0H06ywdgF_aKavBuPmwRMmqJcXDQjPVw',
    appId: '1:200194026999:web:6b7b6ed1791ef7787912f2',
    messagingSenderId: '200194026999',
    projectId: 'messageme-9b9ad',
    authDomain: 'messageme-9b9ad.firebaseapp.com',
    storageBucket: 'messageme-9b9ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoZWzdURBF1DrFodAIYv5ve21fAk_DylY',
    appId: '1:200194026999:android:acc0be028094e5df7912f2',
    messagingSenderId: '200194026999',
    projectId: 'messageme-9b9ad',
    storageBucket: 'messageme-9b9ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0jAOtAKZtLhKS2EuNfhOIHH5ZwmXYejA',
    appId: '1:200194026999:ios:40b48046ff2538307912f2',
    messagingSenderId: '200194026999',
    projectId: 'messageme-9b9ad',
    storageBucket: 'messageme-9b9ad.appspot.com',
    iosBundleId: 'com.example.messageme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0jAOtAKZtLhKS2EuNfhOIHH5ZwmXYejA',
    appId: '1:200194026999:ios:4f32b01fd5c5c3fe7912f2',
    messagingSenderId: '200194026999',
    projectId: 'messageme-9b9ad',
    storageBucket: 'messageme-9b9ad.appspot.com',
    iosBundleId: 'com.example.messageme.RunnerTests',
  );
}
